const User ={
    list1: null,
    name: null,
    report1_Classification:null,
    report2_Classification:null,
    report3_Classification:null,
    report1_ComboClassification :null,
    report2_ComboClassification :null,
    report3_ComboClassification :null,
    report1_label :null,
    report2_label:null,
    report3_label :null,    
    report1_IsActive:null,
    report2_IsActive:null,
    report3_IsActive :null,
    conversionFormula2:null,
    DefaultUOM:null,
    BrandCount:null,
    entityvar:null,
    collectionvar:null,
    itemidvar:null,
    ptrvar:null,
    bpcvar:null,
    itemnamevar:null,
    qty_1:null,
    qty_2:null,
    unit_small:null,
    unit_large:null,
    rate:null,
    Amount:null,
    orderidvar:null,
    Shop_Id:null,
    Shop_name:null,
    PlannedDate:null,
    Time:null,
    location:null,
    Remarks:null,
    Meeting_Id:null
}

export default User;